Contact.html finalizado y versión final
4GeeksAcademy/ejercicio-colaborativo-destruction-team pull request #13
Opened 2024-11-01 12:53 UTC by LuisFlor7

2024-11-03 19:35 UTC, ScarzoJ requested changes

2024-11-03 19:35 UTC, ScarzoJ commented on website/assets/css/style.css
This change completely erases the previous styles work, are you sure you can do this here?

2024-11-03 19:35 UTC, ScarzoJ commented on website/templates/contact.html
>  </div>
The ending of the file has some issues, the last two `div` tags are unnecessary and you should probably swap the `form` in line 22 with the `div` in line 21

2024-11-03 22:37 UTC, p3drac0 approved these changes
Me voy a dormir contento con este trozo de código tan bonito

2024-11-04 10:48 UTC, battanair approved these changes
Está precioso

2024-11-04 11:59 UTC, ScarzoJ approved these changes

2024-11-04 11:59 UTC, merged