tagline
4GeeksAcademy/ejercicio-colaborativo-destruction-team pull request #8
Opened 2024-10-29 19:33 UTC by battanair

la tagline

2024-10-29 19:33 UTC, LuisFlor7 submitted a review, later dismissed

2024-10-30 08:48 UTC, ScarzoJ requested changes

2024-10-30 08:48 UTC, ScarzoJ commented on website/templates/tagline.html
> +
Remove the starting newline and format the document

2024-10-30 08:48 UTC, ScarzoJ commented on website/templates/navbar.html
>  <!-- your html code here -->
Remove the example boilerplate

2024-10-30 15:39 UTC, LuisFlor7 approved these changes

2024-10-30 15:41 UTC, Diegocoros approved these changes

2024-10-30 17:45 UTC, LuisFlor7 approved these changes

2024-10-30 18:33 UTC, closed without merging